//! MUSE-10: the behavioral taste model v0.
//!
//! Recomputes an account's `taste_signals` -> `taste_profile` (+
//! `taste_context_centroids`) from `watch_stats` + `ratings` + `watchlist`
//! (spec §3.4, `S96-muse-foundation.md` MUSE-10). Named `taste_model` (a
//! directory, not `src/taste.rs`/`src/taste/`) so it can't be mistaken for
//! — or collide with — MUSE-03's already-shipped `crate::models::taste`
//! (the table row types) or `crate::repo::taste` (the CRUD layer this module
//! builds on top of): this module is the *derivation* on top of those, not
//! a replacement for either.
//!
//! ## Signal weighting (the auditable atoms, [`signals`])
//! Every watch/rating/watchlist fact becomes one `taste_signals` row with a
//! fixed base weight (finish `+1.0`, each rewatch beyond the first `+2.5`,
//! abandonment `-1.5`, an explicit rating scaled around its midpoint, a
//! watchlist add a mild `+0.3` bumped further once fulfilled). These are
//! stored *undecayed* — recency-weighting is applied at aggregation time
//! (below), not baked into the stored signal, so the raw signal log stays a
//! stable, auditable record of "what happened" independent of when it's
//! later read.
//!
//! ## Recency decay ([`signals::recency_weight`])
//! An exponential half-life decay: a signal's effective weight at
//! aggregation time is `stored_weight * 0.5^(days_since_observed /
//! HALF_LIFE_DAYS)`. Default half-life is 180 days (~6 months) — recent
//! viewing dominates the profile, but a signal never drops to exactly zero
//! (it just keeps halving), so a account's long history is never fully
//! erased, only outweighed by what they've watched lately.
//!
//! ## Profile aggregation ([`profile`])
//! Recency-weighted sums of the signal log, joined out to genre/person/
//! decade/keyword dimensions, folded into `taste_profile`'s
//! `genre_affinity`/`person_affinity`/`keyword_affinity` jsonb columns (see
//! [`profile`]'s module doc for the one documented schema divergence: decade
//! affinity has no dedicated column, so it nests under `keyword_affinity`).
//! `overall_centroid` is the recency-and-rewatch-weighted mean of finished
//! titles' MUSE-08 embeddings (skipping any title that has none yet).
//! `taste_context_centroids` buckets finished `play_sessions` into
//! weekend/weekday x time-of-day contexts and averages each bucket's
//! embeddings.
//!
//! ## `model_notes` via Chord ([`chord_client`])
//! A short natural-language taste summary generated by calling Chord's
//! OpenAI-compatible `/v1/chat/completions` endpoint with the computed
//! affinities. Best-effort and NEVER fails the recompute: if `CHORD_URL`
//! isn't configured, or the call errors for any reason, `model_notes` is
//! simply left `None` (matches the graceful-degrade posture of every other
//! optional integration in this crate — `OllamaEmbedClient`, `SearxngClient`,
//! `NewsClient`, `TmdbClient`, etc.).
//!
//! ## Idempotency ([`recompute::recompute_taste`])
//! `recompute_taste` is the whole thing's entry point: it deletes and
//! re-derives every *automatic* `taste_signals` row for the account (never
//! touching a human-authored `curation_note`), recomputes every affinity
//! dimension and centroid from scratch, and full-replace-upserts
//! `taste_profile` + `taste_context_centroids` (both already
//! full-replace-upsert in `repo::taste`, per MUSE-03). Re-running with no
//! new behavior is a no-op in effect (same signals deleted and reinserted,
//! same profile computed) — safe to call on a schedule or on demand.
//! Multi-user strict: every step is scoped to one `account_id`; taste is
//! never blended across accounts (spec §3.2 `accounts` comment).

pub mod chord_client;
pub mod profile;
pub mod recompute;
pub mod signals;

pub use chord_client::ChordClient;
pub use recompute::recompute_taste;
