//! **The golden probe corpus** — real `ffprobe` documents from the real
//! library, with their expected parse results, committed and diffed on every
//! run (S130-A `MPRB-04`).
//!
//! ## What this replaces
//! Before this item, the probe parser's evidence was: a dozen hand-written
//! documents, and exactly one real capture (`LIVE_DOLBY_VISION_STREAM`, a
//! single `-select_streams v:0` stream). Hand-written fixtures prove a parser
//! is self-consistent. They do not prove it agrees with `ffprobe`, and this
//! project has been bitten by that difference twice already (MUSE #109, #106).
//!
//! ## The two premises this item was specified on, both of which were STALE
//! The spec for this item (`specs/S130-A-maestro-probe.md`, 91 commits behind)
//! says fixtures must be operator-captured because there is no `ffprobe`, and
//! that a survey walker must be built. Both were checked before any of this was
//! written, and both are false:
//!
//! - **`ffprobe` IS installed on <host>** — `5.1.9-0+deb12u1`, confirmed by
//!   running it, on the host that mounts the library at `/srv/media`. Every
//!   document in this corpus was produced by it. Note that
//!   [`crate::media::probe`]'s own module docs still say the opposite in
//!   several places; those are corrected by this item where they are
//!   load-bearing.
//! - **The survey walker exists and has already run the whole library** —
//!   `foundry::survey::survey_files` behind `POST /ops/foundry/survey`,
//!   `examined: 16221`, `truncated: false`, `readiness: surveyed`. Its 7
//!   `probe_failed` files are in this corpus.
//!
//! ## What the corpus covers, and why these shapes
//! Not a random sample. A random draw from this library is h264/aac Matroska
//! twelve times over, which is the stream-copy path and proves almost nothing.
//! Each fixture is here because it is the *worst real case* of something:
//!
//! | fixture | why |
//! |---|---|
//! | `dv_hdr_hevc_4k` | Dolby Vision: the `DOVI configuration record` side-data the DV refusal rests on, on a cropped 3832x2068 frame |
//! | `hdr10_no_dolby_vision` | HDR10 **without** DV — the shape that must NOT be refused as DV |
//! | `cover_art_mjpeg` | 4 `attached_pic` mjpeg streams alongside the feature: the filter that stops artwork being planned as video |
//! | `legacy_msmpeg4v2_avi` | the oldest shape in the library, and a real `"level": -99` |
//! | `dvd_vob_data_stream` | an MPEG-PS `dvd_nav_packet` data stream — the thing that makes a file undecidable |
//! | `multi_audio_eac3` | 11 audio streams, 24 subtitles, per-track dispositions |
//! | `anime_attachments_fonts` | 11 font attachments plus an ASS subtitle track |
//! | `extreme_40_attachments` | the library's attachment maximum |
//! | `extreme_61_subtitles` | the library's subtitle maximum — **61**, not the 42 recorded in `foundry::validate` |
//! | `extreme_66_streams_2video` | the library's stream-count maximum, and 2 video streams |
//! | `frame_rate_base_differs_from_average` | the only real file found where `r_frame_rate` != `avg_frame_rate` |
//! | `fail_ebml_*` (7) | every `probe_failed` file the full-library survey found |
//!
//! The 7 failures are the most valuable rows in the corpus. A parser that has
//! only ever seen healthy input is untested exactly where its behaviour
//! matters — and these files are why `build_ffprobe_args` uses `-v error`
//! rather than `-v quiet`: at `-v quiet` all seven rendered as
//! `"...is not media: "`, a dangling colon and no diagnostic. The committed
//! stderr proves the fix, because it contains the real cause.
//!
//! ## How the corpus was produced, and how to add to it
//! [`crate::media::probe_capture`] is the scrubber. Raw captures are dropped
//! into `tests/golden/probe/_raw/` (git-ignored, never committed) and
//! [`mint_fixtures_from_raw_captures`] — an `#[ignore]`d test, run by hand —
//! scrubs them into the committed corpus. No new binary target, no env var:
//! the presence of the `_raw` directory is the trigger.
//!
//! ## Why the `.expected` files are not the only assertion
//! An `.expected` file is generated by the parser it is meant to be guarding,
//! so on its own it proves only that the parser is stable. That catches
//! regressions and nothing else. So every fixture ALSO has a hand-written
//! assertion below stating what is true about that file independently — 61
//! subtitles, DV profile 8, 4 pieces of cover art — and
//! [`every_fixture_has_a_hand_written_assertion`] refuses to let a fixture be
//! added without one.

use std::path::{Path, PathBuf};

use super::probe::{parse_probe_json, MediaProbe, ProbeError, ProbeState};

/// `tests/golden/probe/` at the crate root, via the build-time constant — the
/// same mechanism `endpoint_tests::golden_support` uses, and not a hardcoded
/// path, so this works from any worktree.
fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/probe")
}

/// Where hand-dropped raw captures live. Git-ignored: a raw capture carries
/// the operator's absolute paths and titles, and the entire point of the
/// scrubber is that only its OUTPUT is ever committed.
fn raw_dir() -> PathBuf {
    corpus_dir().join("_raw")
}

/// A successful capture: the scrubbed `ffprobe` JSON document.
fn ok_path(name: &str) -> PathBuf {
    corpus_dir().join(format!("{name}.json"))
}

/// A failed capture: `{ "exit_code": .., "stderr": .., "stdout": .. }`.
fn failure_path(name: &str) -> PathBuf {
    corpus_dir().join(format!("{name}.failure.json"))
}

/// The golden parse result, as rendered by [`render`] / [`render_error`].
fn expected_path(name: &str) -> PathBuf {
    corpus_dir().join(format!("{name}.expected"))
}

/// Render a [`MediaProbe`] as deterministic, diffable text.
///
/// Text rather than JSON because these goldens are read by a human in a review
/// diff, and because a field ADDED to `MediaProbe` without being rendered here
/// would silently not be covered — which
/// [`the_rendering_covers_every_field_of_the_parsed_probe`] is what refuses.
///
/// Floats are printed at fixed precision. `f64` formatting is deterministic in
/// Rust, but pinning the precision means a golden cannot drift on a value whose
/// last digit is an artefact of the division that produced it (`24000/1001`).
fn render(p: &MediaProbe) -> String {
    let mut out = String::new();
    out.push_str(&format!("container: {}\n", p.container));
    out.push_str(&format!("duration_secs: {}\n", opt_f64(p.duration_secs)));
    out.push_str(&format!("format_bitrate_bps: {:?}\n", p.format_bitrate_bps));
    out.push_str(&format!("size_bytes: {:?}\n", p.size_bytes));
    out.push_str(&format!("title: {:?}\n", p.title));
    out.push_str(&format!("chapter_count: {}\n", p.chapter_count));
    out.push_str(&format!("data_stream_count: {}\n", p.data_stream_count));
    out.push_str(&format!(
        "unindexed_stream_count: {}\n",
        p.unindexed_stream_count
    ));
    out.push_str(&format!("other_stream_count: {}\n", p.other_stream_count));
    out.push_str(&format!("video_count: {}\n", p.video.len()));
    out.push_str(&format!("audio_count: {}\n", p.audio.len()));
    out.push_str(&format!("subtitle_count: {}\n", p.subtitles.len()));
    out.push_str(&format!("attachment_count: {}\n", p.attachments.len()));

    for v in &p.video {
        out.push_str(&format!(
            "video index={} codec={} size={:?}x{:?} bitrate={:?} pix_fmt={:?} profile={:?} \
             tag={:?} level={:?} bits_per_raw_sample={:?} r_fps={} avg_fps={} range={:?} \
             transfer={:?} primaries={:?} space={:?} attached_pic={}\n",
            v.index,
            v.codec,
            v.width,
            v.height,
            v.bitrate_bps,
            v.pix_fmt,
            v.profile,
            v.codec_tag,
            v.level,
            v.bits_per_raw_sample,
            opt_f64(v.frame_rate_fps),
            opt_f64(v.avg_frame_rate_fps),
            v.color_range,
            v.color_transfer,
            v.color_primaries,
            v.color_space,
            v.attached_pic,
        ));
        for d in &v.side_data {
            out.push_str(&format!(
                "  side_data kind={:?} dv_profile={:?} dv_bl_compat={:?} rpu={:?} bl={:?} el={:?}\n",
                d.kind,
                d.dv_profile,
                d.dv_bl_signal_compatibility_id,
                d.rpu_present,
                d.bl_present,
                d.el_present,
            ));
        }
    }
    for a in &p.audio {
        out.push_str(&format!(
            "audio index={} codec={} channels={:?} layout={:?} sample_rate={:?} lang={:?} \
             bitrate={:?} profile={:?} default={} forced={}\n",
            a.index,
            a.codec,
            a.channels,
            a.channel_layout,
            a.sample_rate_hz,
            a.language,
            a.bitrate_bps,
            a.profile,
            a.default,
            a.forced,
        ));
    }
    for s in &p.subtitles {
        out.push_str(&format!(
            "subtitle index={} codec={} lang={:?} default={} forced={} hearing_impaired={} \
             bitmap={}\n",
            s.index,
            s.codec,
            s.language,
            s.default,
            s.forced,
            s.hearing_impaired,
            super::probe::is_bitmap_subtitle_codec(&s.codec),
        ));
    }
    for a in &p.attachments {
        out.push_str(&format!(
            "attachment index={} codec={} filename={:?}\n",
            a.index, a.codec, a.filename
        ));
    }
    for n in &p.notes {
        out.push_str(&format!("note: {n}\n"));
    }
    out
}

/// Fixed-precision float rendering, so a golden pins the value and not the
/// last bit of a division.
fn opt_f64(v: Option<f64>) -> String {
    match v {
        None => "None".to_string(),
        Some(v) => format!("Some({v:.6})"),
    }
}

/// Render a [`ProbeError`] golden: the classification AND the operator-facing
/// message, because both are things this corpus exists to pin.
fn render_error(e: &ProbeError) -> String {
    format!(
        "error_variant: {}\nis_retryable: {}\nstate: {}\nmessage: {}\n",
        variant_name(e),
        e.is_retryable(),
        e.state().as_str(),
        e,
    )
}

fn variant_name(e: &ProbeError) -> &'static str {
    match e {
        ProbeError::ToolMissing { .. } => "ToolMissing",
        ProbeError::Spawn { .. } => "Spawn",
        ProbeError::ExitFailure { .. } => "ExitFailure",
        ProbeError::MalformedOutput { .. } => "MalformedOutput",
        ProbeError::Timeout { .. } => "Timeout",
        ProbeError::NoStreams => "NoStreams",
        ProbeError::OutputTooLarge { .. } => "OutputTooLarge",
    }
}

/// A committed failure capture.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct FailureCapture {
    /// `ffprobe`'s exit code. `None` would mean "killed by a signal"; every
    /// row in this corpus is `Some(1)`.
    exit_code: Option<i32>,
    /// Whether the process exited successfully. Carried separately from the
    /// code for the same reason [`super::probe::interpret_probe_output`] takes
    /// both.
    success: bool,
    /// Scrubbed stderr — the diagnostic, which is the whole value here.
    stderr: String,
    /// Scrubbed stdout. `ffprobe` emits an empty JSON envelope even on a
    /// failure, and that it does so is itself worth pinning.
    stdout: String,
}

// --- the corpus manifest ---------------------------------------------------

/// Every successfully-probed fixture, by name.
///
/// A hand-written literal, deliberately NOT a directory listing: a list derived
/// from the filesystem agrees with the filesystem by construction, so a fixture
/// silently deleted would shrink the list rather than fail a test.
/// [`the_corpus_on_disk_matches_the_manifest`] cross-checks the two.
const OK_FIXTURES: &[&str] = &[
    "anime_attachments_fonts",
    "cover_art_mjpeg",
    "dv_hdr_hevc_4k",
    "dvd_vob_data_stream",
    "extreme_40_attachments",
    "extreme_61_subtitles",
    "extreme_66_streams_2video",
    "frame_rate_base_differs_from_average",
    "hdr10_no_dolby_vision",
    "legacy_msmpeg4v2_avi",
    "multi_audio_eac3",
];

/// Every failure fixture, by name — the 7 `probe_failed` files from the
/// 16,221-file survey, and all 7 of them.
///
/// The count is asserted, not just the membership: "some failures are covered"
/// is not the claim this corpus makes.
const FAILURE_FIXTURES: &[&str] = &[
    "fail_ebml_blade_47_ronin",
    "fail_ebml_savage_salvation",
    "fail_ebml_south_park",
    "fail_ebml_wednesday_s01e03",
    "fail_ebml_wednesday_s01e05",
    "fail_ebml_wednesday_s01e07",
    "fail_ebml_wednesday_s01e08",
];

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("golden corpus file {path:?} is missing or unreadable: {e}"))
}

/// Parse a committed OK fixture through the production parser.
fn probe_of(name: &str) -> MediaProbe {
    parse_probe_json(&read(&ok_path(name)))
        .unwrap_or_else(|e| panic!("fixture {name} must parse, got {e}"))
}

/// Run a committed failure fixture through the production interpretation step
/// — not through a rule restated here.
fn error_of(name: &str) -> ProbeError {
    let c: FailureCapture = serde_json::from_str(&read(&failure_path(name)))
        .unwrap_or_else(|e| panic!("failure fixture {name} must deserialize: {e}"));
    match super::probe::interpret_probe_output(
        c.success,
        c.exit_code,
        c.stdout.as_bytes(),
        c.stderr.as_bytes(),
    ) {
        Err(e) => e,
        Ok(p) => panic!("failure fixture {name} must not produce a probe, got {p:?}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::media::probe_capture::{residual_pii, scrub_probe_document, scrub_stderr};

    // --- the golden comparison ---------------------------------------------

    /// Every successfully-probed fixture still parses to exactly what it
    /// parsed to when it was committed.
    #[test]
    fn every_ok_fixture_matches_its_committed_expectation() {
        for name in OK_FIXTURES {
            let rendered = render(&probe_of(name));
            let expected = read(&expected_path(name));
            assert_eq!(
                expected.trim_end(),
                rendered.trim_end(),
                "fixture {name} drifted from its committed parse result. If this is an \
                 intentional parser change, re-mint the corpus (see \
                 `mint_fixtures_from_raw_captures`); otherwise it is a regression."
            );
        }
    }

    /// The same, for the 7 files the full-library survey could not read.
    #[test]
    fn every_failure_fixture_matches_its_committed_expectation() {
        for name in FAILURE_FIXTURES {
            let rendered = render_error(&error_of(name));
            let expected = read(&expected_path(name));
            assert_eq!(expected.trim_end(), rendered.trim_end(), "fixture {name} drifted");
        }
    }

    /// The golden mechanism has to be able to FAIL. A comparison against a
    /// file that is regenerated by the thing it guards can be vacuous, so this
    /// alters a parsed probe and asserts the rendering actually changes.
    #[test]
    fn the_golden_rendering_detects_a_changed_parse_result() {
        let mut p = probe_of("dv_hdr_hevc_4k");
        let before = render(&p);
        p.video[0].level = p.video[0].level.map(|l| l + 1);
        assert_ne!(before, render(&p), "a changed field must change the golden");

        let mut p2 = probe_of("extreme_61_subtitles");
        let before2 = render(&p2);
        p2.subtitles.pop();
        assert_ne!(before2, render(&p2), "a dropped stream must change the golden");
    }

    // --- the corpus is what it claims to be --------------------------------

    /// The manifest and the directory agree, in BOTH directions: a fixture on
    /// disk that no test names is dead weight that proves nothing, and a
    /// manifest entry with no file is a claim with no evidence.
    #[test]
    fn the_corpus_on_disk_matches_the_manifest() {
        let mut on_disk_ok = Vec::new();
        let mut on_disk_fail = Vec::new();
        for entry in std::fs::read_dir(corpus_dir()).expect("the corpus directory must exist") {
            let entry = entry.expect("readable dir entry");
            let file_name = entry.file_name().to_string_lossy().into_owned();
            // `_raw/` is the git-ignored drop box and is not part of the
            // corpus; `README.md` documents it.
            if entry.path().is_dir() || file_name == "README.md" {
                continue;
            }
            if let Some(stem) = file_name.strip_suffix(".failure.json") {
                on_disk_fail.push(stem.to_string());
            } else if let Some(stem) = file_name.strip_suffix(".json") {
                on_disk_ok.push(stem.to_string());
            }
        }
        on_disk_ok.sort();
        on_disk_fail.sort();
        assert_eq!(on_disk_ok, OK_FIXTURES, "OK_FIXTURES vs tests/golden/probe/");
        assert_eq!(
            on_disk_fail, FAILURE_FIXTURES,
            "FAILURE_FIXTURES vs tests/golden/probe/"
        );
    }

    /// All 7 of the survey's `probe_failed` files, not a sample of them.
    #[test]
    fn all_seven_surveyed_probe_failures_are_in_the_corpus() {
        assert_eq!(
            FAILURE_FIXTURES.len(),
            7,
            "the 2026-08-02 full-library survey (examined 16221, truncated false) reported \
             exactly 7 probe_failed files; the corpus covers all of them"
        );
    }

    /// Every fixture is named by a hand-written assertion, so a fixture cannot
    /// be added and left asserted-on only by its self-generated `.expected`
    /// file.
    ///
    /// Reads THIS file's own source and looks for the assertion by NAME, not
    /// for a mention: a fixture listed in the manifest and in the module's doc
    /// table would otherwise be "mentioned" twice while nothing states a fact
    /// about it.
    #[test]
    fn every_fixture_has_a_hand_written_assertion() {
        let src = include_str!("probe_golden.rs");
        // Counted, not just looped. A loop over an empty (or emptied) list
        // passes without checking anything — a mutation that made this
        // iterate over nothing survived the whole suite until this counter
        // was added.
        let mut checked = 0usize;
        for name in OK_FIXTURES {
            let want = format!("fn the_hand_written_facts_about_{name}()");
            assert!(
                src.contains(&want),
                "fixture {name} has no `{want}` — a golden regenerated by the parser it \
                 guards proves stability, not correctness"
            );
            checked += 1;
        }
        assert_eq!(checked, OK_FIXTURES.len(), "every OK fixture must have been checked");
        assert!(checked >= 11, "the corpus is not supposed to shrink; checked {checked}");
        // The 7 failures share one test, which lists them as literals.
        //
        // The search string is anchored to the DEFINITION (newline plus
        // indentation), not to the bare name — the bare name also occurs in
        // this very test, and matching that occurrence made this check inspect
        // its own body instead of the assertion's. Caught by the check
        // failing, which is the argument for writing it this way round.
        let start = src
            .find("\n    fn the_hand_written_facts_about_the_seven_ebml_failures()")
            .expect("the shared failure test must exist");
        let body = &src[start..];
        let end = body.find("\n    /// ").unwrap_or(body.len());
        for name in FAILURE_FIXTURES {
            assert!(
                body[..end].contains(name),
                "failure fixture {name} is not named in the shared failure assertion"
            );
        }
    }

    // --- the corpus is clean ------------------------------------------------

    /// The PII guarantee, checked over the committed bytes rather than
    /// asserted about the scrubber.
    ///
    /// This is what the public mirror's PII gate would otherwise be the first
    /// thing to notice. That gate is a working mechanism and this does not
    /// replace it — it is here so it never has to fire.
    /// `README.md` is the one file here the sweep skips, and the skip is
    /// bounded rather than open-ended.
    ///
    /// [`residual_pii`] is calibrated for `ffprobe` data, not for prose: the
    /// README necessarily writes `src/media/probe_capture.rs`, which the
    /// path rule reads as a path (correctly — it is one). Exempting prose is a
    /// carve-out, so it is a carve-out of exactly one NAMED file, and
    /// [`the_corpus_on_disk_matches_the_manifest`] is what stops a second
    /// non-data file appearing under it.
    const SWEEP_EXEMPT: &str = "README.md";

    #[test]
    fn no_committed_corpus_file_contains_residual_pii() {
        let mut checked = 0usize;
        let mut exempted = 0usize;
        for entry in std::fs::read_dir(corpus_dir()).expect("corpus dir") {
            let entry = entry.expect("dir entry");
            if entry.path().is_dir() {
                continue;
            }
            if entry.file_name().to_string_lossy() == SWEEP_EXEMPT {
                exempted += 1;
                continue;
            }
            let body = read(&entry.path());
            let hits = residual_pii(&body);
            assert!(
                hits.is_empty(),
                "committed corpus file {:?} contains residual PII: {hits:?}",
                entry.path()
            );
            checked += 1;
        }
        assert_eq!(exempted, 1, "exactly one prose file may be exempt");
        // A sweep over an empty directory passes vacuously. Pin the count so
        // this cannot silently become a no-op.
        let want = OK_FIXTURES.len()          // one .json per OK fixture
            + FAILURE_FIXTURES.len()          // one .failure.json per failure
            + OK_FIXTURES.len()
            + FAILURE_FIXTURES.len(); // one .expected per fixture
        assert_eq!(checked, want, "swept {checked} data files, expected {want}");
    }

    /// The committed fixtures are fixed points of the scrubber, so a
    /// difference on re-scrub means the rule changed rather than that the
    /// corpus is stale.
    #[test]
    fn every_committed_fixture_is_a_fixed_point_of_the_scrubber() {
        for name in OK_FIXTURES {
            let body = read(&ok_path(name));
            let again = scrub_probe_document(&body, name)
                .unwrap_or_else(|e| panic!("re-scrubbing {name} must succeed: {e}"));
            assert_eq!(body, again, "fixture {name} is not a fixed point of the scrubber");
        }
    }

    /// ...and the sweep above is not passing because `residual_pii` stopped
    /// working. A document with the shape the corpus is made of, but carrying
    /// a real path, must be caught.
    #[test]
    fn the_corpus_pii_sweep_would_catch_a_dirty_fixture() {
        let dirty = read(&ok_path("legacy_msmpeg4v2_avi"))
            .replace("fixture-legacy_msmpeg4v2_avi.bin", "/srv/media/MUSIC/x/y.avi");
        let hits = residual_pii(&dirty);
        assert!(!hits.is_empty(), "a re-dirtied fixture must be caught");
    }

    // --- the hand-written facts --------------------------------------------
    //
    // Everything below states, independently of any generated file, what is
    // true of a specific real file in the operator's library. These are the
    // assertions that would survive deleting every `.expected`.

    /// Dolby Vision, on the shape the DV refusal actually rests on.
    #[test]
    fn the_hand_written_facts_about_dv_hdr_hevc_4k() {
        let p = probe_of("dv_hdr_hevc_4k");
        assert_eq!(p.container, "matroska,webm");
        let v = p.primary_video().expect("a feature video stream");
        assert_eq!(v.codec, "hevc");
        // Real 4K releases are CROPPED. A rule that assumes 3840x2160 misfiles
        // this one, which is the whole reason this fixture is 3832x2068.
        assert_eq!((v.width, v.height), (Some(3832), Some(2068)));
        assert_eq!(v.pix_fmt.as_deref(), Some("yuv420p10le"));
        // MPRB-03 fields, on a real document rather than a written one.
        assert_eq!(v.level, Some(150), "HEVC 5.0 is ffprobe level 150");
        assert_eq!(v.color_range.as_deref(), Some("tv"));
        assert_eq!(v.color_transfer.as_deref(), Some("smpte2084"));
        assert_eq!(v.color_primaries.as_deref(), Some("bt2020"));
        let d = v
            .side_data
            .iter()
            .find(|d| d.kind == "DOVI configuration record")
            .expect("the DOVI record ffprobe really emits under -show_streams");
        assert_eq!(d.dv_profile, Some(8));
        assert_eq!(d.rpu_present, Some(true));
        // Chapters are not streams; `-show_chapters` is why they are here at
        // all, and the transcode argv promises to carry them.
        assert_eq!(p.chapter_count, 11);
        assert!(p.audio.len() >= 2 && !p.subtitles.is_empty());
    }

    /// HDR10 with **no** Dolby Vision — the negative case for the DV rule.
    /// Without it, "we detect DV" and "we call everything HDR DV" look alike.
    #[test]
    fn the_hand_written_facts_about_hdr10_no_dolby_vision() {
        let p = probe_of("hdr10_no_dolby_vision");
        let v = p.primary_video().expect("video");
        assert_eq!(v.codec, "hevc");
        assert_eq!(v.color_transfer.as_deref(), Some("smpte2084"), "PQ, so HDR10");
        assert_eq!(v.color_primaries.as_deref(), Some("bt2020"));
        assert!(
            !v.side_data
                .iter()
                .any(|d| d.kind.contains("DOVI") || d.dv_profile.is_some()),
            "this file carries no DV record: {:?}",
            v.side_data
        );
        assert_ne!(v.codec_tag.as_deref(), Some("dvh1"));
        assert_ne!(v.codec_tag.as_deref(), Some("dvhe"));
    }

    /// Cover art. Four `attached_pic` mjpeg streams sit alongside the feature
    /// in this real file; treated as video they would each be an unacceptable
    /// codec and would order a full re-encode of a file that is fine.
    #[test]
    fn the_hand_written_facts_about_cover_art_mjpeg() {
        let p = probe_of("cover_art_mjpeg");
        assert_eq!(p.video.len(), 1, "only the feature stream survives the filter");
        assert_eq!(p.primary_video().expect("video").codec, "h264");
        assert!(
            p.video.iter().all(|v| !v.attached_pic),
            "no artwork may remain in the video list"
        );
        // Vanished-but-counted: the artwork is not silently dropped.
        assert_eq!(p.other_stream_count, 4, "the 4 mjpeg cover images are counted");
    }

    /// The oldest shape in the library — and a real negative `level`, which
    /// `as_u32` must fold to `None` rather than carry as a level nothing can
    /// satisfy. This value was NOT invented for a test; ffprobe reports `-99`
    /// for this file.
    #[test]
    fn the_hand_written_facts_about_legacy_msmpeg4v2_avi() {
        let p = probe_of("legacy_msmpeg4v2_avi");
        assert_eq!(p.container, "avi");
        let v = p.primary_video().expect("video");
        assert_eq!(v.codec, "msmpeg4v2");
        assert_eq!(v.level, None, "ffprobe reports -99 here; a level cannot be negative");
        assert_eq!(v.codec_tag.as_deref(), Some("mp42"), "lowercased from MP42");
        assert_eq!(p.audio.len(), 1);
        assert_eq!(p.audio[0].codec, "mp3");
        assert_eq!(p.audio[0].sample_rate_hz, Some(22050), "not the usual 48k");
        assert_eq!(p.audio[0].channel_layout.as_deref(), Some("mono"));
        assert_eq!(p.subtitles.len(), 0);
    }

    /// A DVD rip: an MPEG-PS `dvd_nav_packet` data stream, which Foundry
    /// cannot carry and which therefore makes the file undecidable rather than
    /// being dropped quietly.
    #[test]
    fn the_hand_written_facts_about_dvd_vob_data_stream() {
        let p = probe_of("dvd_vob_data_stream");
        assert_eq!(p.container, "mpeg");
        assert_eq!(p.data_stream_count, 1, "the nav packet is counted, not ignored");
        assert_eq!(p.primary_video().expect("video").codec, "mpeg2video");
        // Bitmap subtitles, through the single shared vocabulary — and this is
        // the first time a real ffprobe `codec_name` has confirmed the
        // descriptor spelling that `BITMAP_SUBTITLE_CODECS` was written from
        // FFmpeg source alone.
        assert!(p.subtitles.iter().any(|s| s.codec == "dvd_subtitle"));
        assert!(p
            .subtitles
            .iter()
            .all(|s| crate::media::probe::is_bitmap_subtitle_codec(&s.codec)));
    }

    /// Eleven audio streams with per-track dispositions — the shape a
    /// "which track is default" rule gets wrong.
    #[test]
    fn the_hand_written_facts_about_multi_audio_eac3() {
        let p = probe_of("multi_audio_eac3");
        assert_eq!(p.audio.len(), 11);
        assert!(p.audio.iter().filter(|a| a.default).count() <= 1, "at most one default");
        assert!(p.audio.iter().any(|a| a.codec == "eac3"));
        assert!(
            p.audio.iter().filter(|a| a.language.is_some()).count() >= 10,
            "a multi-language release must carry language tags"
        );
        assert_eq!(p.subtitles.len(), 24);
        assert!(p.audio.iter().all(|a| a.sample_rate_hz == Some(48000)));
        assert!(p.audio.iter().any(|a| a.channel_layout.as_deref() == Some("5.1(side)")));
    }

    /// Fonts. Losing these makes an ASS subtitle track render in a fallback
    /// face while the encode reports success — the exact false-claim class the
    /// probe module exists to prevent.
    #[test]
    fn the_hand_written_facts_about_anime_attachments_fonts() {
        let p = probe_of("anime_attachments_fonts");
        assert_eq!(p.attachments.len(), 11);
        assert!(
            p.attachments.iter().all(|a| a.filename.is_some()),
            "an attachment with no filename cannot be remuxed by name"
        );
        assert!(p.attachments.iter().any(|a| a.codec == "ttf"));
        assert!(p.subtitles.iter().any(|s| s.codec == "ass"));
        assert!(
            p.subtitles
                .iter()
                .all(|s| !crate::media::probe::is_bitmap_subtitle_codec(&s.codec)),
            "ASS is a text subtitle format"
        );
    }

    /// The library's attachment maximum.
    #[test]
    fn the_hand_written_facts_about_extreme_40_attachments() {
        let p = probe_of("extreme_40_attachments");
        assert_eq!(p.attachments.len(), 40, "measured maximum in this library");
        assert!(p.attachments.len() < crate::media::probe::MAX_STREAMS);
    }

    /// The library's subtitle maximum — **61**, measured.
    ///
    /// `foundry::validate` records 42 as the worst case in three places. That
    /// number is stale: a scan of every file in this library with 12 or more
    /// streams (1,346 of them) found 61 subtitles on this one. It matters
    /// because every subtitle stream is stream-copied and verified
    /// positionally, so this is the shape most likely to expose a mapping bug,
    /// and a bound sized for 42 is a bound sized for the wrong library.
    #[test]
    fn the_hand_written_facts_about_extreme_61_subtitles() {
        let p = probe_of("extreme_61_subtitles");
        assert_eq!(p.subtitles.len(), 61);
        assert!(
            p.subtitles.len() > 42,
            "the measured worst case exceeds the 42 recorded in foundry::validate"
        );
        // Indices are absolute and the argv maps by absolute index, so they
        // must be distinct and must not have been renumbered by the parser.
        let mut idx: Vec<u32> = p.subtitles.iter().map(|s| s.index).collect();
        let n = idx.len();
        idx.sort_unstable();
        idx.dedup();
        assert_eq!(idx.len(), n, "subtitle indices must be distinct");
        assert_eq!(p.unindexed_stream_count, 0);
        assert!(p.subtitles.iter().filter(|s| s.default).count() <= 1);
    }

    /// The library's stream-count maximum, and a file with two real video
    /// streams — so `primary_video` picking the first is exercised against a
    /// document where there is genuinely a second.
    #[test]
    fn the_hand_written_facts_about_extreme_66_streams_2video() {
        let p = probe_of("extreme_66_streams_2video");
        let total = p.video.len()
            + p.audio.len()
            + p.subtitles.len()
            + p.attachments.len()
            + p.data_stream_count
            + p.other_stream_count;
        assert_eq!(total, 66, "every stream is accounted for in exactly one bucket");
        assert!(
            total < crate::media::probe::MAX_STREAMS,
            "the real maximum must be far below the {} cap",
            crate::media::probe::MAX_STREAMS
        );
        assert_eq!(p.subtitles.len(), 59);
        assert_eq!(p.audio.len(), 5);
    }

    /// `r_frame_rate` and `avg_frame_rate` are kept as two fields because they
    /// genuinely disagree on real files, and this is one: ffprobe reports a
    /// base rate of `24000/1001` and an average of `2997/125` for it.
    ///
    /// Without this fixture nothing in the corpus could tell the two fields
    /// apart — every other real document has them equal, so a parser that read
    /// one field into both would produce identical goldens.
    #[test]
    fn the_hand_written_facts_about_frame_rate_base_differs_from_average() {
        let p = probe_of("frame_rate_base_differs_from_average");
        let v = p.primary_video().expect("video");
        let r = v.frame_rate_fps.expect("a base rate");
        let a = v.avg_frame_rate_fps.expect("an average rate");
        assert_ne!(
            r, a,
            "this fixture exists BECAUSE the two rates differ; if they stopped differing the \
             corpus would no longer distinguish the fields"
        );
        assert!((r - 23.976_023_976).abs() < 1e-6, "24000/1001, got {r}");
        assert!((a - 23.976).abs() < 1e-9, "2997/125, got {a}");
        assert_eq!(p.container, "avi");
    }

    /// The 7 failures, as one fact each: `ffprobe` gave a verdict, so this is
    /// a statement about the FILE and retrying is a loop that never converges.
    ///
    /// And — the reason `-v error` replaced `-v quiet` — the message names the
    /// cause. Under `-v quiet` all seven of these rendered as
    /// `"...is not media: "`, a dangling colon.
    #[test]
    fn the_hand_written_facts_about_the_seven_ebml_failures() {
        for name in [
            "fail_ebml_blade_47_ronin",
            "fail_ebml_savage_salvation",
            "fail_ebml_south_park",
            "fail_ebml_wednesday_s01e03",
            "fail_ebml_wednesday_s01e05",
            "fail_ebml_wednesday_s01e07",
            "fail_ebml_wednesday_s01e08",
        ] {
            let e = error_of(name);
            match &e {
                ProbeError::ExitFailure { code, stderr } => {
                    assert_eq!(*code, Some(1), "{name}");
                    assert!(
                        stderr.contains("EBML header parsing failed"),
                        "{name}: the real cause must survive into the error: {stderr:?}"
                    );
                }
                other => panic!("{name}: expected ExitFailure, got {other:?}"),
            }
            assert!(!e.is_retryable(), "{name}: ffprobe answered; it will answer the same");
            assert_eq!(e.state(), ProbeState::ProbeFailed, "{name}");
            let msg = e.to_string();
            assert!(
                !msg.ends_with("is not media: "),
                "{name}: a failure that cannot state its cause is the -v quiet bug: {msg:?}"
            );
        }
    }

    /// The failure fixtures pin something the OK fixtures cannot: `ffprobe`
    /// emits an empty JSON envelope on stdout even when it fails, and that
    /// envelope must NOT be read as a describable file.
    #[test]
    fn a_failed_probes_empty_envelope_is_never_read_as_a_media_file() {
        let c: FailureCapture =
            serde_json::from_str(&read(&failure_path("fail_ebml_south_park"))).expect("json");
        assert!(!c.stdout.trim().is_empty(), "ffprobe does write an envelope");
        // Parsed on its own, that envelope is `NoStreams` — never an empty
        // `MediaProbe`, which the planner would read as "this file has no
        // video" and act on.
        assert_eq!(parse_probe_json(&c.stdout), Err(ProbeError::NoStreams));
        // And the production interpretation step never gets that far, because
        // the non-zero exit is checked first.
        assert!(matches!(
            error_of("fail_ebml_south_park"),
            ProbeError::ExitFailure { .. }
        ));
    }

    /// The extraction that made the above possible must actually be the code
    /// production runs, not a parallel copy.
    #[test]
    fn the_two_probe_entry_points_share_one_interpretation_step() {
        let src = include_str!("probe.rs");
        assert_eq!(
            src.matches("interpret_probe_output(").count(),
            3,
            "one definition plus exactly two call sites (sync and async) — a third \
             restatement of the exit rule is the drift this extraction removed"
        );
        assert_eq!(
            src.matches("return Err(ProbeError::ExitFailure {").count(),
            1,
            "the exit-status rule must be written once"
        );
    }

    /// The renderer must mention every field of the parsed types, or a field
    /// added later is silently outside the corpus's coverage.
    ///
    /// Reads the struct definitions out of `probe.rs` and checks each field
    /// name appears in `render`. Crude, and it is the kind of check that is
    /// worth exactly what it costs: it cannot be fooled by a field that was
    /// added and never rendered.
    #[test]
    fn the_rendering_covers_every_field_of_the_parsed_probe() {
        let src = include_str!("probe.rs");
        let render_src = {
            let start = include_str!("probe_golden.rs")
                .find("fn render(p: &MediaProbe)")
                .expect("render must exist");
            let body = &include_str!("probe_golden.rs")[start..];
            let end = body.find("\nfn opt_f64").expect("render must end");
            body[..end].to_string()
        };

        for struct_name in [
            "pub struct MediaProbe {",
            "pub struct VideoStream {",
            "pub struct AudioStream {",
            "pub struct SubtitleStream {",
            "pub struct AttachmentStream {",
            "pub struct StreamSideData {",
        ] {
            let start = src.find(struct_name).unwrap_or_else(|| panic!("{struct_name}"));
            let body = &src[start + struct_name.len()..];
            let end = body.find("\n}").expect("struct must close");
            for line in body[..end].lines() {
                let line = line.trim();
                if !line.starts_with("pub ") || !line.ends_with(',') {
                    continue;
                }
                let field = line
                    .trim_start_matches("pub ")
                    .split(':')
                    .next()
                    .expect("field name")
                    .trim();
                assert!(
                    render_src.contains(field),
                    "{struct_name} field `{field}` is not rendered into the golden output, so \
                     no fixture covers it"
                );
            }
        }
    }

    // --- minting ------------------------------------------------------------

    /// Turn raw captures in `tests/golden/probe/_raw/` into committed
    /// fixtures. **Ignored**: it writes files, and it only does anything when
    /// an operator has put raw captures there.
    ///
    /// Run with `cargo test --bin muse -- --ignored mint_fixtures`.
    ///
    /// It is the path that produced this corpus, and it does one thing beyond
    /// scrubbing that no CI test can: it parses the RAW document and the
    /// SCRUBBED document and refuses to write a fixture unless the two agree
    /// on everything except the deliberately-synthesized title. That is what
    /// makes "the scrubber changed nothing the parser reads" a checked claim
    /// about the actual corpus rather than about a small example.
    #[test]
    #[ignore = "writes fixtures; only meaningful with raw captures in tests/golden/probe/_raw/"]
    fn mint_fixtures_from_raw_captures() {
        let raw = raw_dir();
        if !raw.is_dir() {
            eprintln!("no {raw:?} — nothing to mint");
            return;
        }
        let mut minted = 0usize;
        let mut entries: Vec<_> = std::fs::read_dir(&raw)
            .expect("raw dir")
            .map(|e| e.expect("entry").path())
            .filter(|p| p.to_string_lossy().ends_with(".stdout.json"))
            .collect();
        entries.sort();

        for stdout_path in entries {
            let name = stdout_path
                .file_name()
                .expect("file name")
                .to_string_lossy()
                .trim_end_matches(".stdout.json")
                .to_string();
            let stdout = read(&stdout_path);
            let stderr = read(&raw.join(format!("{name}.stderr.txt")));
            let rc: i32 = read(&raw.join(format!("{name}.rc.txt")))
                .trim()
                .parse()
                .expect("rc must be an integer");

            if rc == 0 {
                let scrubbed = scrub_probe_document(&stdout, &name)
                    .unwrap_or_else(|e| panic!("{name}: {e}"));

                // The check that only exists here: raw vs scrubbed, parsed.
                let mut before = parse_probe_json(&stdout)
                    .unwrap_or_else(|e| panic!("{name}: raw must parse: {e}"));
                let mut after = parse_probe_json(&scrubbed)
                    .unwrap_or_else(|e| panic!("{name}: scrubbed must parse: {e}"));
                before.title = None;
                after.title = None;
                for (b, a) in before.attachments.iter_mut().zip(after.attachments.iter_mut()) {
                    b.filename = None;
                    a.filename = None;
                }
                assert_eq!(
                    before, after,
                    "{name}: scrubbing changed something the parser reads"
                );

                std::fs::write(ok_path(&name), &scrubbed).expect("write fixture");
                std::fs::write(
                    expected_path(&name),
                    render(&parse_probe_json(&scrubbed).expect("parses")),
                )
                .expect("write expectation");
            } else {
                let capture = FailureCapture {
                    exit_code: Some(rc),
                    success: false,
                    stderr: scrub_stderr(&stderr, &name).unwrap_or_else(|e| panic!("{name}: {e}")),
                    stdout,
                };
                let rendered = serde_json::to_string_pretty(&capture).expect("serialize") + "\n";
                let hits = residual_pii(&rendered);
                assert!(hits.is_empty(), "{name}: residual PII in failure capture: {hits:?}");
                std::fs::write(failure_path(&name), &rendered).expect("write failure fixture");
                std::fs::write(
                    expected_path(&name),
                    render_error(&super::super::probe::interpret_probe_output(
                        capture.success,
                        capture.exit_code,
                        capture.stdout.as_bytes(),
                        capture.stderr.as_bytes(),
                    )
                    .expect_err("a failure capture must produce an error")),
                )
                .expect("write expectation");
            }
            minted += 1;
        }
        eprintln!("minted {minted} fixtures into {:?}", corpus_dir());
    }
}
